### ISSUE TITLE
Host config parameter ignored

### ISSUE THREAD

**Issue by rrezel** [riolet/SAM#9]
Here
db = web.database(dbn='mysql', user=dbconfig.params['user'], pw=dbconfig.params['passwd'], db=dbconfig.params['db'], port=dbconfig.params['port'])

https://github.com/riolet/SAM/blob/dev/common.py#L28

**Comment by rrezel** [comment]
Also here:
https://github.com/riolet/SAM/blob/de6f009b105d923ebc8b3378d3580aba1c49ae3a/dbaccess.py#L20

**Comment by JoePelz** [comment]
Does the above address what you meant?

**Comment by rrezel** [comment]
It does. Thanks!
